# Generated by Django 2.1.2 on 2018-11-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=40, verbose_name='Никнейм'),
        ),
    ]
