# Generated by Django 2.1.2 on 2018-11-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=40, verbose_name='Никнейм'),
        ),
    ]
