# Generated by Django 2.1.2 on 2018-11-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
    ]
