# Generated by Django 2.1.2 on 2018-11-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_remove_answer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
