# Generated by Django 2.1.2 on 2018-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_user_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Заголовок ярлыка'),
        ),
    ]
