# Generated by Django 2.1.2 on 2018-11-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20181106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=40, unique=True, verbose_name='Никнейм'),
        ),
    ]
