# Generated by Django 2.1.2 on 2018-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20181106_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
