# Generated by Django 2.1.2 on 2018-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20181106_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Никнейм'),
        ),
    ]
