# Generated by Django 2.1.2 on 2018-11-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions', '0023_auto_20181106_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
